package com.samskivert.depot;

import java.util.List;
import java.util.Set;

import org.junit.Test;

import com.google.common.collect.Iterables;

import com.samskivert.depot.clause.Where;

import static org.junit.Assert.assertEquals;

public class GeneratedValueTest
{
    @Test public void insertAutoGeneratedValue ()
    {
        PersistenceContext pc = TestBase.createPersistenceContext();
        DepotRepository dr = new DepotRepository(pc) {
            @Override
            protected void getManagedRecords (Set<Class<? extends PersistentRecord>> classes) {
                classes.add(GeneratedValueRecord.class);
            }
        };
        GeneratedValueRecord rec = new GeneratedValueRecord();
        rec.value = 2;
        assertEquals(0, rec.recordId);
        assertEquals(1, dr.insert(rec));
        assertEquals(1, rec.recordId);
        List<GeneratedValueRecord> recs =
            dr.findAll(GeneratedValueRecord.class, new Where(GeneratedValueRecord.VALUE.eq(2)));
        assertEquals(1, Iterables.getOnlyElement(recs).recordId);
    }
}
