//
// Depot library - a Java relational persistence library
// http://code.google.com/p/depot/source/browse/trunk/LICENSE

package com.samskivert.depot;

import java.util.List;
import java.util.Set;

import org.junit.Before;
import org.junit.Test;

import com.google.common.collect.Iterables;

import static org.junit.Assert.assertEquals;

public class GeneratedValueTest
{
    @Before public void createRepository ()
    {
        PersistenceContext pc = TestBase.createPersistenceContext();
        _dr = new DepotRepository(pc) {
            @Override
            protected void getManagedRecords (Set<Class<? extends PersistentRecord>> classes) {
                classes.add(GeneratedValueRecord.class);
                classes.add(AllGeneratedRecord.class);
            }
        };

    }

    @Test public void insertAutoGeneratedValue ()
    {
        GeneratedValueRecord rec = new GeneratedValueRecord();
        rec.value = 2;
        assertEquals(0, rec.recordId);
        assertEquals(1, _dr.insert(rec));
        assertEquals(1, rec.recordId);
        List<GeneratedValueRecord> recs = _dr.from(GeneratedValueRecord.class).
            where(GeneratedValueRecord.VALUE.eq(2)).select();
        assertEquals(1, Iterables.getOnlyElement(recs).recordId);
    }

    @Test public void insertAllGeneratedValue ()
    {
        AllGeneratedRecord rec = new AllGeneratedRecord();
        assertEquals(0, rec.recordId);
        assertEquals(1, _dr.insert(rec));
        assertEquals(1, rec.recordId);
    }

    protected DepotRepository _dr;
}
