//
// $Id$
//
// Depot library - a Java relational persistence library
// Copyright (C) 2006-2010 Michael Bayne and Pär Winzell
//
// This library is free software; you can redistribute it and/or modify it
// under the terms of the GNU Lesser General Public License as published
// by the Free Software Foundation; either version 2.1 of the License, or
// (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

package com.samskivert.depot;

import java.util.List;
import java.util.Set;

import org.junit.Test;

import com.google.common.collect.Iterables;

import static org.junit.Assert.assertEquals;

public class GeneratedValueTest
{
    @Test public void insertAutoGeneratedValue ()
    {
        PersistenceContext pc = TestBase.createPersistenceContext();
        DepotRepository dr = new DepotRepository(pc) {
            @Override
            protected void getManagedRecords (Set<Class<? extends PersistentRecord>> classes) {
                classes.add(GeneratedValueRecord.class);
            }
        };
        GeneratedValueRecord rec = new GeneratedValueRecord();
        rec.value = 2;
        assertEquals(0, rec.recordId);
        assertEquals(1, dr.insert(rec));
        assertEquals(1, rec.recordId);
        List<GeneratedValueRecord> recs = dr.from(GeneratedValueRecord.class).
            where(GeneratedValueRecord.VALUE.eq(2)).select();
        assertEquals(1, Iterables.getOnlyElement(recs).recordId);
    }
}
